# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    - id: run-tests
      name: run pytest
      language: script
      entry: ./tests/repo_test_runner.sh
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: check-case-conflict
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=800'] # Our expected results files are fairly large
    - id: no-commit-to-branch # Work in branches please -- not in main
      args: ['--branch', 'main']
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
