[tool.poetry]
name = "generatorcore"
version = "0.9.0"
description = "LocalZero Generator core."
authors = ["Benedikt Grundmann <benedikt.grundmann@gmail.com>"]
include = [
  "generatorcore/py.typed"
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pre-commit = "^2.17.0"
black = {version = "^21.12b0", allow-prereleases = true}
pytest-cov = "^3.0.0"
pyright = "^0.0.13"

[tool.pyright]
include = ["generatorcore", "commands", "tests"]
typeCheckingMode = "basic"
pythonVersion = "3.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
